### ISSUE TITLE
Interfaces - Lesson 4 Abstract 

### ISSUE THREAD

**Issue by DilanTanner** [compscirunner/7-11-tst-100#2]
Text references a getAge() default method that hasn't been declared.  Location is midway down the page. 
![Screenshot 2022-07-21 135530](https://user-images.githubusercontent.com/15604760/180294379-4ed3a0fb-36dc-4f3d-b1ab-9cf629c24bf1.png)

**Comment by compscirunner** [comment]
fixed commit ad206d768
