### ISSUE TITLE
Lesson 9 Design Patterns Hands on

### ISSUE THREAD

**Issue by UltimateTrainer** [compscirunner/7-11-tst-100#3]
![CowInsteadOfCat](https://user-images.githubusercontent.com/18106403/180865328-ead21f99-863a-47a5-8378-08d7e9c37961.png)
If input a cat, we should output a Cat instead of a cow.

**Comment by jrobertsDev** [comment]
Fixed in Exeter repo commit [c6017e4](https://github.com/woz-u/lms-curriculum/commit/c6017e499d949f9585edb49ceede5cb8fe8d1ce5)
