### ISSUE TITLE
Lesson 8, chapter 7, interfaces activity part 1.

### ISSUE THREAD

**Issue by SicusD** [compscirunner/7-11-tst-100#7]
Exeter instructions state to make a "public Rectangle" class. This will cause an error. rectangle should have no modifier

**Comment by jrobertsDev** [comment]
Fixed in Exeter commits [9937318](https://github.com/woz-u/lms-curriculum/commit/99373182611517b79381353dfb7abff825e10a83) and [a62ce5a](https://github.com/woz-u/lms-curriculum/commit/a62ce5a06a3c60afe5deb1010fea0954e501266c)
