### ISSUE TITLE
Broken image links in TestNG unit (Java and SQL recap)

### ISSUE THREAD

**Issue by compscirunner** [compscirunner/7-11-tst-100#8]
All images are broken.

**Comment by jrobertsDev** [comment]
Fixed in Exeter curriculum repo commits [6a36ced](https://github.com/woz-u/lms-curriculum/commit/6a36ced0c5be25b1177e393c0765e28d32b5311f) and [2d5a307](https://github.com/woz-u/lms-curriculum/commit/2d5a307d49011a06c6e10b4b75b0e34133a25c2f)
